#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login:
    path: /login
    controller: App\Controller\SecurityController::login
    
profilEnabled:
    path: /profilEnabled
    controller: App\Controller\ProfilEnabledController::profilEnabled
                               
files:
    path: /files
    controller: App\Controller\LanController::files
        
formulaireEleve:
    path: /formulaireEleve
    controller: App\Controller\LanController::formulaireEleve

formulaireG:
    path: /formulaireG
    controller: App\Controller\LanController::formulaireG

followCompany:
    path: /followCompany
    controller: App\Controller\LanController::followCompany

followTraining:
    path: /followTraining
    controller: App\Controller\LanController::followTraining

test:
    path: /test
    controller: App\Controller\LanController::test

## ****************************  Document 

getInfoDoc: 
    path: /getInfoDoc/{iddr}
    controller: App\Controller\DocumentController::getInfoDoc

upload: 
    path: /upload
    controller: App\Controller\DocumentController::upload

downloadlist:
    path: /downloadlist
    controller: App\Controller\DocumentController::downloadlist

download:
    path: /download/{id}
    controller: App\Controller\DocumentController::download

deletedocument:
    path: /deletedocument/{id}
    controller: App\Controller\DocumentController::deletedocument

stageForm:
    path: /stageForm
    controller: App\Controller\StageFormController::stageForm

## App\Controller\LanController

formations:
    path: /formations
    controller: App\Controller\LanController::formations

documents:
    path: /documents
    controller: App\Controller\LanController::documentOff

aide:
    path: /aide
    controller: App\Controller\LanController::aide

# compte
compte:
    path: /compte
    controller: App\Controller\CompteController::monCompte

modifInfoMonCompte:
    path: /modifInfoMonCompte
    controller: App\Controller\CompteController::modifInfoMonCompte

compte_modif_password:
    path: /modifier_mon_password
    controller: App\Controller\CompteModifPasswordController::compte_modif_password

## App\Controller\InscriptionController

inscriptionEntreprise:
    path: /inscriptionEntreprise
    controller: App\Controller\InscriptionController::inscriptionEntreprise

inscriptionApprenti:
    path: /inscriptionApprenti
    controller: App\Controller\InscriptionController::inscriptionApprenti

inscriptionMA:
    path: /inscriptionMA
    controller: App\Controller\InscriptionController::inscriptionMA
    
inscriptionInd:
    path: /inscriptionInd
    controller: App\Controller\InscriptionController::inscriptionInd

inscriptionFormateur:
    path: /inscriptionFormateur
    controller: App\Controller\InscriptionController::inscriptionFormateur

inscriptionEleve:
    path: /inscriptionEleve
    controller: App\Controller\InscriptionController::inscriptionEleve

barSession:
    path: /barSession
    controller: App\Controller\BarController::barSession
    
addUser:
    path: /addUser/{role}/{roleName}
    controller: App\Controller\InscriptionController::addUser

addUserSession:
    path: /addUserSession/{session}/{role}/{roleName}
    controller: App\Controller\InscriptionController::addUserSession


    
## App\Controller\DashController

dashOFPrincipal:
    path: /dashOFPrincipal
    controller: App\Controller\DashController::dashOFPrincipal

    
dashApp:
    path: /dashApp
    controller: App\Controller\DashController::dashApp

    
dashEntreprise:
    path: /dashEntreprise
    controller: App\Controller\DashController::dashEntreprise


dashFormateur:
    path: /dashFormateur
    controller: App\Controller\DashController::dashFormateur

dashMA:
    path: /dashMA
    controller: App\Controller\DashController::dashMA


## **************** SESSION

addSession:
    path: /addSession
    controller: App\Controller\DashController::addSession

deleteSession:
    path: /deleteSession/{session}
    controller: App\Controller\DashController::deleteSession

dashOFSession:
    path: /dashOFSession/{session}
    controller: App\Controller\DashController::dashOFSession



editApprenti:
    path: /feditApprenti/{userID}
    controller: App\Controller\DashController::editApprenti

editUser:
    path: /editUser/{user}
    controller: App\Controller\ProfilController::editUser

listApprentis:
    path: /listApprentis/{session}
    controller: App\Controller\DashController::listApprentis

listUsersSession:
    path: /listUsersSession/{session}/{role}/{roleName}
    controller: App\Controller\DashController::listUsersSession

listUsersEntreprise:
    path: /listUsersEntreprise/{entreprise}/{role}/{roleName}
    controller: App\Controller\DashController::listUsersEntreprise

listFormateurs:
    path: /listFormateurs/{session}
    controller: App\Controller\DashController::listFormateurs

listMA:
    path: /listMA/{session}
    controller: App\Controller\DashController::listMA
   
listAllAprentis: 
    path: /listAllAprentis
    controller: App\Controller\DashController::listAllAprentis

listAllFormateurs: 
    path: /listAllFormateurs
    controller: App\Controller\DashController::listAllFormateurs

listAllEntreprises: 
    path: /listAllEntreprises
    controller: App\Controller\DashController::listAllEntreprises

listAllMA: 
    path: /listAllMA
    controller: App\Controller\DashController::listAllMA


# ********************** Annuaire **************************

annuairePopup:
    path: /annuairePopup
    controller: App\Controller\LanController::annuairePopup

annuaireTest:
    path: /annuaireTest
    controller: App\Controller\LanController::annuaireTest

annuaireR:
    path: /annuaireR/{role}
    controller: App\Controller\LanController::annuaireR

annuaireRS:
    path: /annuaireRS/{role}/{session}
    controller: App\Controller\LanController::annuaireRS

annuaire:
    path: /annuaire
    controller: App\Controller\LanController::annuaire

# ********************** les Profils **************************


profilOF_APP: 
    path: /profilOF_APP/{user}
    controller: App\Controller\ProfilController::profilOF_APP

profilOF_Formateur: 
    path: /profilOF_Formateur/{user}
    controller: App\Controller\ProfilController::profilOF_Formateur

profilOF_MA: 
    path: /profilOF_MA/{user}
    controller: App\Controller\ProfilController::profilOF_MA

profilOF_Entreprise: 
    path: /profilOF_Entreprise/{user}
    controller: App\Controller\ProfilController::profilOF_Entreprise

profilAPP_OF: 
    path: /profilAPP_OF/{user}
    controller: App\Controller\ProfilController::profilAPP_OF

profilAPP_Formateur: 
    path: /profilAPP_Formateur/{user}
    controller: App\Controller\ProfilController::profilAPP_Formateur

profilAPP_MA: 
    path: /profilAPP_MA/{user}
    controller: App\Controller\ProfilController::profilAPP_MA
    
profilAPP_Entreprise: 
    path: /profilAPP_Entreprise/{user}
    controller: App\Controller\ProfilController::profilAPP_Entreprise

profilFOR_OF: 
    path: /profilFOR_OF/{user}
    controller: App\Controller\ProfilController::profilFOR_OF
 
profilFOR_APP: 
    path: /profilFOR_APP/{user}
    controller: App\Controller\ProfilController::profilFOR_APP
          
profilFOR_MA: 
    path: /profilFOR_MA/{user}
    controller: App\Controller\ProfilController::profilFOR_MA
     
profilFOR_Entreprise: 
    path: /profilFOR_Entreprise/{user}
    controller: App\Controller\ProfilController::profilFOR_Entreprise

profilMA_OF: 
    path: /profilMA_OF/{user}
    controller: App\Controller\ProfilController::profilMA_OF
 
profilMA_APP: 
    path: /profilMA_APP/{user}
    controller: App\Controller\ProfilController::profilMA_APP
          
profilMA_FOR: 
    path: /profilMA_FOR/{user}
    controller: App\Controller\ProfilController::profilMA_FOR
     
profilENT_OF: 
    path: /profilENT_OF/{user}
    controller: App\Controller\ProfilController::profilENT_OF
 
profilENT_APP: 
    path: /profilENT_APP/{user}
    controller: App\Controller\ProfilController::profilENT_APP
          
profilENT_FOR: 
    path: /profilENT_FOR/{user}
    controller: App\Controller\ProfilController::profilENT_FOR

     
# ********************** RGPD **************************

rgpdForm:
    path: /rgpdForm
    controller: App\Controller\RGPDController::rgpdForm

# ********************** EVALUATION **************************

saisiEvaluation: 
    path: /saisiEvaluation/{competence}/{app}
    controller: App\Controller\EvaluationController::saisiEvaluation

choiceCompetence: 
    path: /choiceCompetence/{app}/{session}
    controller: App\Controller\EvaluationController::choiceCompetence


