#index:
#    path: /
#    controller: App\Controller\DefaultController::index


inscriptionEleve:
    path: /inscriptionEleve
    controller: App\Controller\LanController::inscriptionEleve

inscriptionEntrepriseAS:
    path: /inscriptionEntrepriseAS

inscriptionFormateur:
    path: /inscriptionFormateur
    controller: App\Controller\LanController::inscriptionFormateur
    
inscriptionEntreprise:
    path: /inscriptionEntreprise
    controller: App\Controller\LanController::inscriptionEntreprise

login:
    path: /login
    controller: App\Controller\LanController::login

                                
dashBoardStudent:
    path: /dashBoardStudent
    controller: App\Controller\LanController::dashBoardStudent

dashBoardSchool:
    path: /dashBoardSchool
    controller: App\Controller\LanController::dashBoardSchool

files:
    path: /files
    controller: App\Controller\LanController::files
    
dashBoardSkill:
    path: /dashBoardSkill
    controller: App\Controller\LanController::dashBoardSkill

getSkillToBe:
    path: /getSkillToBe
    controller: App\Controller\LanController::getSkillToBe

suiviCompetences:
    path: /suiviCompetences
    controller: App\Controller\LanController::suiviCompetences
    
formulaireEleve:
    path: /formulaireEleve
    controller: App\Controller\LanController::formulaireEleve

formulaireG:
    path: /formulaireG
    controller: App\Controller\LanController::formulaireG

dash:
    path: /dash
    controller: App\Controller\LanController::dash

followCompany:
    path: /followCompany
    controller: App\Controller\LanController::followCompany

followTraining:
    path: /followTraining
    controller: App\Controller\LanController::followTraining

test:
    path: /test
    controller: App\Controller\LanController::test

dashBoardEntrprise:
    path: /dashBoardEntrprise
    controller: App\Controller\LanController::dashBoardEntrprise

upload: 
    path: /upload
    controller: App\Controller\DocumentController::upload

downloadlist:
    path: /downloadlist
    controller: App\Controller\DocumentController::downloadlist

download:
    path: /download/{id}
    controller: App\Controller\DocumentController::download

deletedocument:
    path: /deletedocument/{id}
    controller: App\Controller\DocumentController::deletedocument

stageForm:
    path: /stageForm
    controller: App\Controller\StageFormController::stageForm

session:
    path: /session
    controller: App\Controller\LanController::session

formations:
    path: /formations
    controller: App\Controller\LanController::formations

InscriptionEntreprise:
    path: /inscriptionEntreprise
    controller: App\Controller\InscriptionController::InscriptionEntreprise

InscriptionApprenti:
    path: /inscriptionApprenti
    controller: App\Controller\InscriptionController::InscriptionApprenti

InscriptionMA:
    path: /inscriptionMA
    controller: App\Controller\InscriptionController::InscriptionMA

